apiVersion: v1
kind: Service
metadata:
  name: lifesub-web
  labels:
    app: lifesub-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 18080
    protocol: TCP
    name: http
  selector:
    app: lifesub-web
