apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifesub-web
  labels:
    app: lifesub-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifesub-web
  template:
    metadata:
      labels:
        app: lifesub-web
    spec:
      containers:
      - name: lifesub-web
        image: acrdigitalgarage02.azurecr.io/dg0306/lifesub-web:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 18080
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
        volumeMounts:
        - name: runtime-config
          mountPath: /usr/share/nginx/html/runtime-env.js
          subPath: runtime-env.js
      imagePullSecrets:
      - name: acr-auth
      volumes:
      - name: runtime-config
        configMap:
          name: frontend-runtime-config
